// <auto-generated />
using System;
using InformacioniBackand.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InformacioniBackand.Migrations
{
    [DbContext(typeof(DataContexDb))]
    partial class DataContexDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InformacioniBackand.Entities.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Lozinka")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("LozinkaKljuc")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Igraci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DatumRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTima")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Menadzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Lozinka")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("LozinkaKljuc")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menazder");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.NaKlupi", b =>
                {
                    b.Property<int>("IdIgraca")
                        .HasColumnType("int");

                    b.Property<int>("IdUtakmice")
                        .HasColumnType("int");

                    b.ToTable("NaKlupi");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Navijac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BrojClanskeKarte")
                        .HasColumnType("int");

                    b.Property<string>("DatumIstekaRoka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTima")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Lozinka")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("LozinkaKljuc")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StatusReg")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Navijac");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Rezultati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrBodova")
                        .HasColumnType("int");

                    b.Property<int>("BrIzgubljenih")
                        .HasColumnType("int");

                    b.Property<int>("BrNeresenih")
                        .HasColumnType("int");

                    b.Property<int>("BrOdigranihSusreta")
                        .HasColumnType("int");

                    b.Property<int>("BrPobeda")
                        .HasColumnType("int");

                    b.Property<int>("IdTima")
                        .HasColumnType("int");

                    b.Property<string>("Sezona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rezultati");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Tim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DatumOsnivanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdMenadzera")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tim");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Uplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DatumPlacanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdNavijaca")
                        .HasColumnType("int");

                    b.Property<int>("Suma")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Uplata");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.UPrvojPostavi", b =>
                {
                    b.Property<int>("IdIgraca")
                        .HasColumnType("int");

                    b.Property<int>("IdUtakmice")
                        .HasColumnType("int");

                    b.ToTable("UprvojPostavi");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.Utakmica", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("BrCrvenihKartona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrZutihKartona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTima1")
                        .HasColumnType("int");

                    b.Property<int?>("IdTima2")
                        .HasColumnType("int");

                    b.Property<string>("Rezultat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vreme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utakmica");
                });

            modelBuilder.Entity("InformacioniBackand.Entities.ZahteviZaProduzenjeClastva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DatumZahteva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdNavijaca")
                        .HasColumnType("int");

                    b.Property<int>("StatusZahteva")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ZahteviZaProduzenjeClastva");
                });
#pragma warning restore 612, 618
        }
    }
}
